name: buildingos.vision
services:
  # Streaming Server
  zlm:
    image: zlmediakit/zlmediakit:master
    ports:
      - "10081:80"
      - "10554:554"
      - "11935:1935"
      - "18080:8080"
    volumes:
      - ./zlm/config.ini:/opt/media/conf/config.ini
      - ./zlm/www:/opt/media/www/
    restart: always

  # AI Engine (Development Mode)
  ai-engine:
    build: 
      context: ./ai_engine
      dockerfile: Dockerfile.dev
    environment:
      - MQTT_BROKER=buildingos-emqx-prod
      - ZLM_API=http://zlm:80/index/api/
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ai_engine/models:/app/models
      - ./ai_engine/config:/app/config
      - ./ai_engine/src:/app/src # Hot reload support
      - ./zlm/www:/app/www # Shared media storage
    depends_on:
      - zlm
    restart: always
    networks:
      - default
      - buildingos-prod-network

  # Debug Engine (For Visualization)
  debug-engine:
    build: 
      context: ./ai_engine
      dockerfile: Dockerfile.dev
    command: python /app/src/debug_server.py
    environment:
      - CONFIG_PATH=/app/config/config.json
    ports:
      - "5000:5000"
    volumes:
      - ./ai_engine/models:/app/models
      - ./ai_engine/config:/app/config
      - ./ai_engine/src:/app/src
    networks:
      - default
      - buildingos-prod-network

  # Node-RED
  node-red:
    image: nodered/node-red:latest
    ports:
      - "11880:1880"
    volumes:
      - ./node_red_data:/data
    restart: always
    networks:
      - default
      - buildingos-prod-network

networks:
  buildingos-prod-network:
    external: true
